-- Did this person CHOOSE their handle, or did we pick it for them? (2026-09-23, Phase 11)
--
-- V35 generates a handle from somebody's display name so that nobody is stopped mid-signup to
-- invent one. That is the right default, but it leaves a gap the user asked to close: a Google
-- sign-up silently becomes "thanhnguyen" and never sees it, so nobody's handle is really theirs.
--
-- This column is the difference. False means we guessed, and the client asks them to confirm or
-- change it once — pre-filled, so it is one click, not an invention. True means it is theirs:
-- either they typed it at sign-up, or they have been through that prompt, or they edited it in
-- Settings.
--
-- Defaulting to false is deliberate for the rows that already exist: every handle in the table
-- today was generated by V35's backfill, which is exactly the state that deserves a prompt.

alter table profiles add column username_chosen boolean not null default false;
